name: resultfy
description: "A robust utility for handling success and error states in a functional style."
version: 1.0.0
homepage: https://github.com/evandersondev/resultfy

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
